import '../styles/globals.css'
import ParallexProvider from '../components/ParallexProvider'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}


type Props = {
    children: React.ReactNode
}


export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body>
                <ParallexProvider>
                    {children}
                </ParallexProvider>
            </body>
        </html>
    )
}
