export const metadata = {
    title: 'Spotify Clone',
    description: 'Generated by Next.js',
}

export default function Head() {
    return (
        <>
            <title>Spotify Clone</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}